language: python

services:
  - docker

before_install:
- git submodule update --init --recursive
- docker pull docker pull uavcan/toxic:py35-py38

script:
- docker run --rm -v $TRAVIS_BUILD_DIR:/pydsdlgen uavcan/toxic:py35-py38 /bin/sh -c tox
