language: python

services:
  - docker

before_install:
- sudo apt-get install -y tree
- git submodule update --init --recursive
- docker pull uavcan/toxic:py35-py38

install:
- "echo $TRAVIS_BUILD_DIR"

script:
- "docker run --rm -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN -v $TRAVIS_BUILD_DIR:/pydsdlgen uavcan/toxic:py35-py38 /bin/sh -c tox"

after_success:
- tree
