language: python

services:
  - docker

before_install:
- sudo apt-get install -y tree
- git submodule update --init --recursive
- docker pull uavcan/toxic:py35-py38
- pip install codacy-coverage

install:
- "echo $TRAVIS_BUILD_DIR"

script:
- "docker run --rm -v $TRAVIS_BUILD_DIR:/pydsdlgen uavcan/toxic:py35-py38 /bin/sh -c tox"

after_success:
- tree
- python-codacy-coverage -r test/coverage.xml
